### ISSUE TITLE
Clusters not appear anymore

### ISSUE THREAD

**Issue by Narayane** [efremidze/Cluster#102]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description

My clusters are not displayed anymore when I zoom in or zoom out and call `self.clusterManager.reload(mapView: self.mapView)`

I have just replaced 
```
annotationView = ClusterAnnotationView(annotation: annotation, reuseIdentifier: CLUSTER_CELL_REUSE_ID, style: .color(.black), radius: 25))
```
by 
```
annotationView = ClusterAnnotationView(annotation: annotation, reuseIdentifier: CLUSTER_CELL_REUSE_ID)
(annotationView as! ClusterAnnotationView).countLabel.backgroundColor = .black
```
in 
```
func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {}
```

### Environment

- **iOS Version**: 12.1
- **Device(s)**: iPhone XS (simulator), iPhone 5S (simulator)

**Comment by Narayane** [comment]
I have downgraded Cluster from 2.4.1 to 2.2.9 and clusters are visible again. It seems ClusterAnnotationView constructor update in 2.3 to be the problem in my case...

**Comment by efremidze** [comment]
Sorry for the confusion, I've renamed the `ClusterAnnotationView` to `StyledClusterAnnotationView`. It's out in [v2.4.3](https://github.com/efremidze/Cluster/releases/tag/2.4.3).
