### ISSUE TITLE
Markers disappear when map view region changed

### ISSUE THREAD

**Issue by elpatxificador** [efremidze/Cluster#106]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description

I attach a video with the problem.

### Environment

- **iOS Version**: [iOS 12.1]
- **Device(s)**: [Simulator iPhone XR and iPhone 6S device]

### Gif:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2070957/53118895-764d2800-354e-11e9-8316-0a9fc2f46c05.gif)

Congratulations for the project.

Thank you.

**Comment by efremidze** [comment]
Thanks I'll look into it asap.

**Comment by elpatxificador** [comment]
I have the default configuration.

I've also tried changing the ClusterPosition to center and average.

Finally I have also tried to change cellSize and the same problem occurs.

**Comment by efremidze** [comment]
Does disabling `shouldDistributeAnnotationsOnSameCoordinate` fix it?

**Comment by elpatxificador** [comment]
It also happens with:
```swift
manager.shouldDistributeAnnotationsOnSameCoordinate = false
```
I've tried all the configuration combinations and nothing.

**Comment by efremidze** [comment]
I'm unable to reproduce it. Can you reproduce it using the example project?

https://share.icloud.com/photos/0UY9wyvsZLz15ARsI1TFatHgA

**Comment by elpatxificador** [comment]
With the example project I do not have the problem.

Here is an example of my project, what am I doing wrong?

[ClusterExample.zip](https://github.com/efremidze/Cluster/files/2902815/ClusterExample.zip)

Many thanks.

**Comment by efremidze** [comment]
Your marker are being hidden because you are using `displayPriority = .defaultHigh`. An annotation view whose priority is set to `required` is always visible on the map, whereas other priorities may result in the annotation view being hidden.
https://developer.apple.com/documentation/mapkit/mkannotationview/2867298-displaypriority
