### ISSUE TITLE
Crash (fatal error) on annotations removing

### ISSUE THREAD

**Issue by letko-dmitry** [efremidze/Cluster#108]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description

The following fatal error is triggered quite often:
`Fatal error: rect.contains evaluted to true, but none of the children removed the annotation: file /Users/dmitry.letko/Repository/wifimap-ios-workplace/Pods/Cluster/Sources/QuadTree.swift, line 113`

### Environment

- **iOS Version**: 12.1.4
- **Device(s)**: iPhone 7+

**Comment by efremidze** [comment]
What version of Cluster is this happening on?

**Comment by letko-dmitry** [comment]
It’s ‘2.4.6’

**Comment by efremidze** [comment]
Do you have any steps to reproduce?

**Comment by efremidze** [comment]
It should no longer crash in 2.4.8.

**Comment by efremidze** [comment]
It should be fixed in `2.4.8`

**Comment by letko-dmitry** [comment]
Neat, will take a look later.
Btw, I didn't manage to determine exact steps to reproduce the issue.
Thank you
