### ISSUE TITLE
Customize the distance from contested location

### ISSUE THREAD

**Issue by grifas** [efremidze/Cluster#115]
**Is your feature request related to a problem? Please describe.**
On my app, I have a map with a limited zoom level, that is to say I can't zoom in to the max because I don't want to see the exact location of the annotation. When I have a lot of annotations at the same location, they are displayed around the location but as I limited the zoom level I can't see them. (see the picture)

**Describe the solution you'd like**
I would like to customize the distance from contested location to increase it to see the annotations with the same location at my max zoom in.

**Describe alternatives you've considered**
I tested to multiplicate the `distanceFromContestedLocation`.
```
(annotation as? MKPointAnnotation)?.coordinate = annotation.coordinate.coordinate(onBearingInRadians: bearing, atDistanceInMeters: distanceFromContestedLocation * 10)
```

**Additional context**

| Before (at max zoom in) | After (at max zoom in) |
|-------------------------|------------------------|
|    ![IMG_2194](https://user-images.githubusercontent.com/9267969/61856346-3f46be00-aec2-11e9-8bf2-60dcfd818386.jpg)          |        ![IMG_2195](https://user-images.githubusercontent.com/9267969/61856361-453c9f00-aec2-11e9-9230-0b0e00396f39.jpg)                |

**Checklist**
- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

**Comment by efremidze** [comment]
Resolved by #116
