### ISSUE TITLE
Swift Compile Error

### ISSUE THREAD

**Issue by danielmackay1080** [efremidze/Cluster#122]
I have been using your library for a little while now and it was working fine up until about 2-3 weeks ago. I had updated my xcode and cocoapods and then the issue started. i am now unable to build my project. I have updated Cluster to its latest version and this is still happening. Any help on this would be greatly appreciated. Thanks

<img width="323" alt="Screen Shot 2019-11-25 at 11 57 58 AM" src="https://user-images.githubusercontent.com/8395396/69556357-f3447c80-0f7a-11ea-886c-6df43d486918.png">

**Comment by efremidze** [comment]
You need to update to Xcode 11 to support propertyWrappers
