### ISSUE TITLE
how can i add multiple difference cluster?

### ISSUE THREAD

**Issue by allenbbgo** [efremidze/Cluster#134]
hi, i have problem....
i don't know how to create two difference cluster in one map

can you tell me how to add that?
thank you

**Comment by efremidze** [comment]
I would suggest creating multiple ClusterManagers.

**Comment by efremidze** [comment]
If you are referring to one dataset but different UIs, you can customize the UI of the cluster view itself using the delegates.

**Comment by allenbbgo** [comment]
> I would suggest creating multiple ClusterManagers.

thank you so much!!

ok , I have add two ClusterManagers,but i dont know how to make difference color at cluster

my problem is at viewFor function 
if i want to make diffenence cluster color, its change code in viewFor function ? 

this my code

    lazy var carManager: ClusterManager = { [unowned self] in
        let carManager = ClusterManager()
        carManager.delegate = self

        carManager.maxZoomLevel = 17
        carManager.minCountForClustering = 5
        carManager.clusterPosition = .nearCenter

        return carManager
    }()

    lazy var manager: ClusterManager = { [unowned self] in
        let manager = ClusterManager()
        manager.delegate = self

        manager.maxZoomLevel = 17
        manager.minCountForClustering = 1
        manager.clusterPosition = .nearCenter
        
        return manager
    }()

**my problem is in here**
if i want to make diffenence cluster color, its change code in here? 

func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
        if let annotationCluster = annotation as? ClusterAnnotation {

            print("ClusterAnnotation")
            let index = 0
            let identifier = "Cluster\(index)"
            let selection = Selection(rawValue: index)!
            return mapView.annotationView(selection: selection, annotation: annotationCluster, reuseIdentifier: identifier)
          }
}

**Comment by efremidze** [comment]
If you subclass the annotations, you can differentiate between the annotations added to each manager. Use two different subclasses for each manager and check the type when you create the view.

**Comment by allenbbgo** [comment]
i did it!  
,I don’t know how I could have done it without you
I really appreciate it!
