### ISSUE TITLE
Pins grouping issue

### ISSUE THREAD

**Issue by tdimeco** [efremidze/Cluster#15]
Hello again!

As I am adding a lot of pins on my map, I am facing an issue with grouping. The grouping algorithm seems not to be predictive. If I zoom/unzoom a little bit, sometime a pin will be part of group 1, and sometime on group 2. This can lead to weird things (see attached video).

Is it easy to fix or not? :)

[cluster-issue.mp4.zip](https://github.com/efremidze/Cluster/files/986020/cluster-issue.mp4.zip)

**Comment by GranitGjevukaj** [comment]
Hi,

I am facing the exact same issue. The pins will be part of different groups when the map region zooms or changes.

**Comment by jVirus** [comment]
Hello,

I experienced the same behavior. Would nice to find a solution for this issue. I will spend a while digging into this

**Comment by efremidze** [comment]
is this issue happening on both 1.0.4 and 1.0.3?

**Comment by GranitGjevukaj** [comment]
@efremidze yes I pulled the latest code today and it's still the case.

**Comment by efremidze** [comment]
can u try on 1.0.3?

**Comment by tdimeco** [comment]
It's the same on 1.0.3

**Comment by efremidze** [comment]
Investigating

**Comment by GranitGjevukaj** [comment]
Hi @efremidze did you find anything on this issue?

**Comment by efremidze** [comment]
Sorry I haven't had time to solve the problem yet. Ill try to fix it tonight.
