### ISSUE TITLE
Support for multiple Cluster Managers

### ISSUE THREAD

**Issue by GranitGjevukaj** [efremidze/Cluster#16]
Hello,

Kudos for the great work on the library so far :)

I faced an issue when I tried to group pins based on a given type that I have. 
It would be really convenient if I could configure multiple Cluster Manager instances. I've seen that feature in some older libs.

Do you think that would be possible to achieve in your library?

Thank you,
Granit

**Comment by efremidze** [comment]
Yes, what kind of implementation r u looking for? Can u point me to some other libraries that do that?

**Comment by GranitGjevukaj** [comment]
Hello,

This library supports multiple Cluster Managers: https://github.com/choefele/CCHMapClusterController

**Comment by GranitGjevukaj** [comment]
Hello @efremidze ,

Do you have any updates on this last outstanding issues?

Thank you in advance!

Best,
Granit

**Comment by efremidze** [comment]
Ill take a look tonight. Should be easy to support.

**Comment by efremidze** [comment]
I'm almost done adding support. I found the issue.

**Comment by GranitGjevukaj** [comment]
@efremidze did you manage to add this?

**Comment by efremidze** [comment]
I haven't fixed it but basically the cluster manager is removing all the pins and then adding new pins. It should remove only the pins related to the individual manager. If u want to fix that, ill merge it in. I haven't had the time to fully fix it yet.
