### ISSUE TITLE
Unable to access ClusterAnnotationView type:ClusterAnnotationType property

### ISSUE THREAD

**Issue by brisingr002** [efremidze/Cluster#18]
Hello,

commit "710c605aa47f92da52f7f7f5618650ca2a28e64a" changed protection attribute of type property.

```
OLD
public var type: ClusterAnnotationType? {
         didSet {
             configure()
         }
     }
NEW
let type: ClusterAnnotationType

```
What was the reasoning behind this move? Could you please change it back to public?

Thanks a lot.

**Comment by efremidze** [comment]
sorry, my bad. fixing it now. thanks.

**Comment by efremidze** [comment]
Committed to master. Ill make a new version asap, fixing a few bugs first.
