### ISSUE TITLE
Carthage badge is missing

### ISSUE THREAD

**Issue by TofPlay** [efremidze/Cluster#2]
Intresting component 🙂
On your `README.md` [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage) is missing.

**Comment by efremidze** [comment]
I include Carthage in the readme. I feel the badge is unnecessary.

**Comment by TofPlay** [comment]
For sure the badge is up to you. But with the badge we see immediately that the project support carthage. Without It is necessary to scroll the page to see that the project supports carthage.
On this project I scrolled but it is more an exception. Usually if I do not see the badge for carthage I pass on another project.

**Comment by efremidze** [comment]
Sure I can add it
