### ISSUE TITLE
How do I change the picture of the single pin?

### ISSUE THREAD

**Issue by gabber3000** [efremidze/Cluster#22]
Hello,
How do I change the picture of the single pin?
Currently I can only change the color. I would like to put a custom image on the pin-
thank you.

**Comment by efremidze** [comment]
Are you asking how to create a pin with an image?

**Comment by gabber3000** [comment]
Exactly .. i would like to create a pin with an image. I'm using the demo code to the line "if #available (iOS 9.0, *) {" I can not create a pin with image.

` func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
        let color = UIColor(red: 255/255, green: 149/255, blue: 0/255, alpha: 1)
        if let annotation = annotation as? ClusterAnnotation {
            let identifier = "Cluster"
            var view = mapView.dequeueReusableAnnotationView(withIdentifier: identifier)
            if view == nil {
                if let annotation = annotation.annotations.first as? Annotation, let type = annotation.type {
                    
                    view = BorderedClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: type, borderColor: .white)
                } else {
                    view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: .color(color, radius: 25))
                }
            } else {
                view?.annotation = annotation
            }
            return view
        } else {
            let identifier = "Pin"
            var view = mapView.dequeueReusableAnnotationView(withIdentifier: identifier) as? MKPinAnnotationView
            if view == nil {
                
                view = MKPinAnnotationView(annotation: annotation, reuseIdentifier: identifier)
                view?.canShowCallout = true
                
                if #available(iOS 9.0, *) {
                    view?.pinTintColor = color
                    -> Here I have to display the pin with the image <----------------------------------
                } else {
                    view?.pinColor = .green
                }
            } else {
                view?.annotation = annotation
            }
            
          /*  let annotation = Annotation()
            annotation.type = .image(UIImage(named: "pin2"))
            manager.add(annotation)
            view?.annotation = annotation
           */
            
            return view
        }
    }
`

**Comment by gabber3000** [comment]
OK guys;) I solved this way. Now everything works;)
` func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
        let reuseId:String
        switch annotation {
            case is MKUserLocation:
                return nil // blue pulsy dot
            case is ClusterAnnotation:
                reuseId = "Cluster"
                var clusterView = mapView.dequeueReusableAnnotationView(withIdentifier: reuseId)
                clusterView = ClusterAnnotationView.init(annotation: annotation, reuseIdentifier: reuseId, type:.color(UIColor.orange, radius: 25))
                clusterView?.canShowCallout = true
                return clusterView
        default:
            reuseId = "Pin"
            var pinView = mapView.dequeueReusableAnnotationView(withIdentifier: reuseId)
            if pinView != nil {
                pinView!.annotation = annotation
            } else {
                pinView = MKAnnotationView(annotation: annotation, reuseIdentifier: reuseId)
     
                pinView!.image = UIImage.init(named: "pin2")
                pinView!.canShowCallout = true
            }
            return pinView
        }
     }
`

**Comment by kwstasna** [comment]
@gabber3000 Hello and nice solution about the issue. Although does the tap on the cluster mark works with your solution ?
