### ISSUE TITLE
view.bounds must be called from main thread only

### ISSUE THREAD

**Issue by funkenstrahlen** [efremidze/Cluster#25]
![screen shot 2017-06-09 at 14 30 38](https://user-images.githubusercontent.com/144173/26975489-52af2118-4d20-11e7-9a12-9c3c34d3a357.png)

**Comment by efremidze** [comment]
Thanks ill fix that asap

**Comment by MaeseppTarvo** [comment]
@efremidze is it fixed?

**Comment by efremidze** [comment]
yes

**Comment by MaeseppTarvo** [comment]
@efremidze  it is still a problem in the 1.0.7 version.
