### ISSUE TITLE
Selecting an annotation 

### ISSUE THREAD

**Issue by imclean** [efremidze/Cluster#26]
Hi, this might have been raised before but not too sure.

I have a manager which has annotations, obviously some are clustered.
I want to select an annotation programmatically but if it is in a cluster, the view of the annotation is nil and therefore cannot be selected.
How would I select an annotation (i.e. move to the cluster, open the cluster and select the annotation that was inside it)?
I've tried moving to the location where the cluster should be without animation, but it can't be selected somehow.

Any ideas?

**Comment by imclean** [comment]
Ok, I got this to work if I move to the point where the annotation is, zoom in to the region, reload the annotations and select it on a delay:
`let latitude:CLLocationDegrees = location.latitude
  let longitude:CLLocationDegrees = location.longitude
  let latDelta:CLLocationDegrees = 0.0005
  let lonDelta:CLLocationDegrees = 0.0005
  let span = MKCoordinateSpanMake(latDelta, lonDelta)
  let location = CLLocationCoordinate2DMake(latitude, longitude)
  let region = MKCoordinateRegionMake(location, span)
  self.mapView.setRegion(region, animated: false)
  self.manager.reload(self.mapView, visibleMapRect: self.mapView.visibleMapRect)
  delay(delay: 0.3, closure: { 
       self.mapView.selectAnnotation(annotation, animated: true)
  })
`

**Comment by efremidze** [comment]
Ill add a completion block to the reload function to fix this issue.

**Comment by efremidze** [comment]
#24

**Comment by efremidze** [comment]
```
self.manager.reload(self.mapView, visibleMapRect: self.mapView.visibleMapRect) {
    self.mapView.selectAnnotation(annotation, animated: true)
}
```
