### ISSUE TITLE
Cluster Annotation wrongly Removed and re-Added

### ISSUE THREAD

**Issue by Yungbubu** [efremidze/Cluster#30]
Hi!

What a great repo!

I strumbled on something that may be a bug. 

When moving the mapView very slightly, the ClusterManager removes some ClusterAnnotation and re-add them right away. In does not seems to happen with Annotations. 

**Example of logs:** 
Deleting <Cluster.ClusterAnnotation: 0x171884dd0>
Deleting <Cluster.ClusterAnnotation: 0x171887940>
Deleting <Cluster.ClusterAnnotation: 0x175c90770>
Deleting <Cluster.ClusterAnnotation: 0x171892ca0>
Adding <Cluster.ClusterAnnotation: 0x171884dd0>
Adding <Cluster.ClusterAnnotation: 0x171887940>
Adding <Cluster.ClusterAnnotation: 0x175c90770>
Adding <Cluster.ClusterAnnotation: 0x171892ca0>

It's not very bad but if you have some processing done in the "viewFor" method of the mapView this is annoying. 

I tried to play with the Set<NSObject> but could not figure out what was wrong. It seems that for some reason some ClusterAnnotations in before and after are considered unequal, whereas they are equal.

Any idea ? 

Any help will be greatly appreciated.

**Comment by melms** [comment]
This issue is very apparent on my device. Just found this code today, maybe I'll come up with solution
