### ISSUE TITLE
Incorrect annotation/clusterAnnotation for zoom level

### ISSUE THREAD

**Issue by melms** [efremidze/Cluster#31]
Same issue in the FB library as well. As I slowly zoom out, my pins pop in and out of a single cluster. I can be entirely zoomed out and have two pins overlapping. I learned that this does not happen on particular zoom levels (2-20), but particular fractions of a zoom level.. if that makes any sense. 

I can't see why it would be returning the wrong annotation type.

**Comment by melms** [comment]
Try with 2-3 annotations on map

**Comment by efremidze** [comment]
I'm not seeing this

**Comment by qu4sar** [comment]
there are news ?

**Comment by efremidze** [comment]
Shouldn't be happening in latest release
