### ISSUE TITLE
Totally wrong cluster count

### ISSUE THREAD

**Issue by MaeseppTarvo** [efremidze/Cluster#32]
Hey! I have tested the project using 2 pins only. If you zoom out a little, it shows cluster count 4 if it has to be one. If something at all

**Comment by efremidze** [comment]
Thanks ill fix asap

**Comment by efremidze** [comment]
I'm not seeing this

**Comment by NSMyself** [comment]
I'm experiencing the same issue to be honest.

**Comment by efremidze** [comment]
Ill do more testing

**Comment by cbarbera80** [comment]
same for me :/

**Comment by efremidze** [comment]
@cbarbera80: can u give me more info?
