### ISSUE TITLE
annotation image

### ISSUE THREAD

**Issue by firatyenidunya** [efremidze/Cluster#4]
I guess there is no way to add images to annotations. I think its gonna be awesome feature for this project.

**Comment by efremidze** [comment]
You can add images.

```
annotation.type = .image(named: "someImage.png")
```

https://github.com/efremidze/Cluster/blob/master/Example/ViewController2.swift

**Comment by firatyenidunya** [comment]
Sorry about that. Totally missed it. I will try. By the way if you could write it down to the readme.md, it would be more efficient in my opinion

**Comment by efremidze** [comment]
yes Ill include that info in the README
