### ISSUE TITLE
Erros Cluster.swift

### ISSUE THREAD

**Issue by andresousaribeiro** [efremidze/Cluster#40]
Hello There,

After install the Cluster pod on my project and without make any further changes. The application got 3 erros.

These 2 :

visibleAnnotations.subtract(Set(toRemove as! [NSObject]))
visibleAnnotations.formUnion(Set(toAdd as! [NSObject]))

With : Type 'NSObject' does not conform to protocol 'MKAnnotation'

And these 1:

let after = Set(clusteredAnnotations as! [NSObject])

With : Type 'NSObject' does not conform to protocol 'MKAnnotation'

It's normal by default the pop to have this erros?

**Comment by efremidze** [comment]
What iOS version? Xcode version?

**Comment by andresousaribeiro** [comment]
I'm using the last version of xcode and iOS 9.0

**Comment by andresousaribeiro** [comment]
But i "resolve" the problem using your code from branch swift 4.0
