### ISSUE TITLE
Question/potential bug: Any reason for allowing duplicate annotations in the ClusterManager?

### ISSUE THREAD

**Issue by ruddct** [efremidze/Cluster#41]
First off, thanks for getting this project started! Loving the simplicity and Swifty-ness and the simplicity  so far, a fresh change of pace compared to CCH and other clustering libraries out there.

A quick question: I'm finding myself needing to wrap all my ClusterManager.add calls in a helper function that detects duplicates. Right now, it's possible to add the same instance to the ClusterManager multiple times (frustrating as it creates a permanent 'cluster' at that location).

Was there a reason for that? It's a little frustrating from a user's perspective, but curious to hear your thoughts.

(Happy to submit a PR for this, pending the response)

**Comment by efremidze** [comment]
Same instance of an annotation or multiple instances of ClusterManagers?

**Comment by ruddct** [comment]
@efremidze It's possible to add the same instance of an annotation multiple times to an individual ClusterManager

**Comment by efremidze** [comment]
I designed the functions around the MKMapView implementation. We should be using sets instead of arrays but I haven't rearchitected it yet. But I agree with you, we shouldn't allow the same instance.

**Comment by ruddct** [comment]
Sounds good, I'll close this for now and chug on it!
