### ISSUE TITLE
How to enable canShowCallout and rightCalloutAccessoryView?

### ISSUE THREAD

**Issue by donbytyqi** [efremidze/Cluster#48]
annotation.canShowCallout = true
annotation.rightCalloutAccessoryView = UIButton

Doesn't seem to work.

**Comment by efremidze** [comment]
on the clusterAnnotation or regular annotation?

**Comment by donbytyqi** [comment]
on the cluster annotation view, sorry should've been more clear.

`annotationView = ClusterAnnotationView(annotation: annotation, reuseIdentifier: annotationIdentifier, type: .image(UIImage(named: "pin.png")))
            annotationView?.isUserInteractionEnabled = true
            annotationView?.canShowCallout = true
            annotationView?.rightCalloutAccessoryView = UIButton(type: .detailDisclosure)`

**Comment by efremidze** [comment]
You need to add it twice
```
if let view = view as? ClusterAnnotationView {
    view.annotation = annotation
    view.configure(with: type)
    view.canShowCallout = true
    view.rightCalloutAccessoryView = SomeView()
} else {
    view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: type)
    view.canShowCallout = true
    view.rightCalloutAccessoryView = SomeView()
}
```

**Comment by donbytyqi** [comment]
That doesn't seem to work as well, is this the right place to put it?

    `func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
        
        guard !annotation.isKind(of: MKUserLocation.self) else {
            return nil
        }
        
        let annotationIdentifier = "AnnotationIdentifier"
        
        var annotationView = mapView.dequeueReusableAnnotationView(withIdentifier: annotationIdentifier)
        
        if annotationView == nil {
            annotationView = ClusterAnnotationView(annotation: annotation, reuseIdentifier: annotationIdentifier, type: .image(UIImage(named: "pin.png")))
            annotationView?.canShowCallout = true
            annotationView?.rightCalloutAccessoryView = UIButton(type: .detailDisclosure)
        } else {
            annotationView!.annotation = annotation
            annotationView?.canShowCallout = true
            annotationView?.rightCalloutAccessoryView = UIButton(type: .detailDisclosure)
        }
        
        return annotationView
        
    }`

**Comment by efremidze** [comment]
```
func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
    
    guard !annotation.isKind(of: MKUserLocation.self) else {
        return nil
    }
    
    let annotationIdentifier = "AnnotationIdentifier"
    
    var annotationView = mapView.dequeueReusableAnnotationView(withIdentifier: annotationIdentifier)
    
    if annotationView == nil {
        annotationView = ClusterAnnotationView(annotation: annotation, reuseIdentifier: annotationIdentifier, type: .image(UIImage(named: "pin.png")))
    } else {
        annotationView!.annotation = annotation
    }
    annotationView?.canShowCallout = true
    annotationView?.rightCalloutAccessoryView = UIButton(type: .detailDisclosure)
    
    return annotationView
    
}
```

**Comment by donbytyqi** [comment]
Still not working, maybe the issue is Swift 4?

**Comment by efremidze** [comment]
swift 4 doesn't affect callouts

**Comment by donbytyqi** [comment]
hmm, okay, I'll just see what's causing this issue. Thanks for the help :)

**Comment by sandman4sure** [comment]
It breaks because of the `layer.masksToBounds = true` in `ClusterAnnotationView`

**Comment by matoxxx** [comment]
I'm having the same issue. How can I display annotation callout?
Can someone show me on example code from this repo?
Thanks for help

**Comment by efremidze** [comment]
This library handles the clustering, you can add a callout by using the [MKMapViewDelegate](https://developer.apple.com/documentation/mapkit/mkmapviewdelegate) methods.

**Comment by ghadeermohameedelmahdy** [comment]
anyone have the solution?
