### ISSUE TITLE
Selecting ClusterAnnotation

### ISSUE THREAD

**Issue by olejnjak** [efremidze/Cluster#5]
Hi, 

I really like your solution as other's I've been using were written in Objective-C and I've run into some bridging issues. But I've run into issue here as well.

Common pattern I want to use is that when user selects cluster, app zooms in to make all annotations in that cluster visible. So I've implemented delegate method to the example to try that.

```swift
func mapView(_ mapView: MKMapView, didSelect view: MKAnnotationView) {
    guard let annotation = view.annotation else { return }
        
    if let cluster = annotation as? ClusterAnnotation {
        mapView.showAnnotations(cluster.annotations, animated: true)
    }
}
```

The behavior I get doesn't look nice. When the cluster is tapped, pins are added to map and when `mapView(regionDidChangeAnimated:)` is called, tapped cluster is removed and if some of the newly added pins are clusters they are transformed to reflect that. Would it be possible to do that in a better way?

Thanks

**Comment by efremidze** [comment]
Fixed in version 1.0.3
