### ISSUE TITLE
Ambiguous use of 'subscript(_:default:)' on Hash swift4, Xcode9

### ISSUE THREAD

**Issue by erdemgc** [efremidze/Cluster#51]
for node in tree.annotations(in: mapRect) {
                    totalLatitude += node.coordinate.latitude
                    totalLongitude += node.coordinate.longitude
                    annotations.append(node)
                    hash[node.coordinate, default: [MKAnnotation]()] += [node] //On This Line
                }

Ambiguous use of 'subscript(_:default:)'

How to fix it?

**Comment by Premal-Khetani** [comment]
@erdemgc 

Kindly add below code in Extension file. 

`extension Dictionary {
    subscript(key: Key, `default` value: Value) -> Value {
        mutating get { return self[key] ?? { self[key] = value; return value }() }
        set { self[key] = newValue }
    }
}`

This solved issue.

**Comment by efremidze** [comment]
Swift 4 added that function. Use [Cluster 1.0.10](https://github.com/efremidze/Cluster/tree/1.0.10) for the Swift 3 version.
