### ISSUE TITLE
Work wrong

### ISSUE THREAD

**Issue by jose46moreno** [efremidze/Cluster#52]
Make a circle of annotations like this image:
![archivo 13-10-17 11 42 19](https://user-images.githubusercontent.com/8105593/31540338-abb9c7d8-b00b-11e7-93b6-7cc3e5a08542.png)

**Comment by efremidze** [comment]
What are you asking?

**Comment by jose46moreno** [comment]
Why appear this annotations making a circle?

I do not programming this.

**Comment by efremidze** [comment]
It's the new iOS 11 annotation

**Comment by jose46moreno** [comment]
i do not mean the appearance.

I mean why do annotations appear by making a circle with two inside it, it is not what I have programmed.

This is an annotation and when I zoom on it appears this circle.

**Comment by efremidze** [comment]
if annotations have the same coordinate, they form a circle. https://github.com/efremidze/Cluster/issues/29

**Comment by jose46moreno** [comment]
It is only one annotations. 

I do not understand why zooming on it generates all those.

**Comment by jose46moreno** [comment]
Sorry, It is already solved.

But, I have another problem.

Why this annotations do not join in a cluster?
![archivo 17-10-17 19 00 01](https://user-images.githubusercontent.com/8105593/31678117-68a57ebe-b36d-11e7-97de-9e089f4b3a40.png)

**Comment by efremidze** [comment]
It might be a bug or `minimumCountForCluster` is causing that.

**Comment by jose46moreno** [comment]
I set minimumCountForCluster equal 2.

**Comment by jose46moreno** [comment]
How can I modify the parameters so that they come together before?

**Comment by efremidze** [comment]
I'm working on a solution.

**Comment by jose46moreno** [comment]
Ok, i am working too.

Let me know if you get it!!

**Comment by efremidze** [comment]
try latest release [2.0.1](https://github.com/efremidze/Cluster/releases/tag/2.0.1)

**Comment by jose46moreno** [comment]
I try release 2.0.1 and the cluster goes crazy. When I zoom out on the map, it does not stop changing its position. 

Please try to solve it.

**Comment by efremidze** [comment]
Im not seeing that issue. What version of Xcode, iOS, device, etc?

**Comment by jose46moreno** [comment]
I am using the latest version of Xcode (Version 9.0.1 (9A1004)), iOS 10, iPhone 5S.

When I zoom, the cluster changes its position on the map.

If you want, let me an email and I will share a video through Dropbox, for example.

Do not take my words as attacks, thank you very much for your work and effort.

I just want to help you, if possible, to improve the library.
