### ISSUE TITLE
Clustor pin is not removing on zoom when pin have Exact Same location. 

### ISSUE THREAD

**Issue by Premal-Khetani** [efremidze/Cluster#53]
Hi,

I am using latest cluster. I am Facing  issue with exact same location pins. 
Here we have requirements for to show annotations for the same locations.  and the locations will be the exact same.  when i tap on cluster pin it zooms in and not removing cluster pin. 

![maplocissue](https://user-images.githubusercontent.com/13691970/31595554-3c256ef8-b25a-11e7-8a5c-4155b9c036a4.gif)

Please Help me ASAP. 

Thank you.

**Comment by efremidze** [comment]
I need to investigate a fix for this.

**Comment by jeon9878** [comment]
Anyone got solution for this ?

**Comment by R0cKET** [comment]
+1

**Comment by efremidze** [comment]
This was fixed in [2.1.0](https://github.com/efremidze/Cluster/releases/tag/2.1.0). Is it still happening for you?

**Comment by jeon9878** [comment]
After updating the pod to https://github.com/efremidze/Cluster/releases/tag/2.1.0 I am getting errors and now my project is gone. 

errors:
/Pods/Cluster/Sources/Cluster.swift:198:25: Cannot subscript a value of type '[CLLocationCoordinate2D : [MKAnnotation]]' with an index of type '(CLLocationCoordinate2D, default: [MKAnnotation])' (aka '(CLLocationCoordinate2D, default: Array<MKAnnotation>)')

/Pods/Cluster/Sources/Cluster.swift:235:21: Cannot convert value of type '[MKAnnotation]' to expected argument type 'inout _'

/Pods/Cluster/Sources/Extensions.swift:59:16: '...' is not a postfix unary operator
