### ISSUE TITLE
Cluster pin changes it's place when drag the map. 

### ISSUE THREAD

**Issue by Premal-Khetani** [efremidze/Cluster#54]
hi, 

having another issue as below. 

When i drag the map i the cluster pin changes it's location. I did print toAdd and toRemove array of annotations with coordinates and the log is attached below. When i drag the map "regionDidChangeAnimated" method called and here we added below line : 

**`clusterManager.reload(MapView, visibleMapRect: MapView.visibleMapRect)`**

and in the reload method i did add below things. 

```
open func reload(_ mapView: MKMapView, visibleMapRect: MKMapRect) {
        
        let zoomScale = ZoomScale(mapView.bounds.width) / visibleMapRect.size.width
        let (toAdd, toRemove) = clusteredAnnotations(mapView, zoomScale: zoomScale, visibleMapRect: visibleMapRect)
        
        for annoadd in toAdd {
            print("Location of toAdd Annotations  : \(annoadd.coordinate)")
        }
        for annorem in toRemove {
            print("Location of toRemove Annotations  : \(annorem.coordinate)")
        }
        mapView.removeAnnotations(toRemove)
        mapView.addAnnotations(toAdd)
        visibleAnnotations.subtract(toRemove)
        visibleAnnotations.add(toAdd)
    }
```
The issue is when i drag or scroll the map the pin changes its Coordinate. please look into GIF. 

Log :  

**NOTE : We are showing annotations not pin on the map.** 

> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.07258800000001, longitude: -81.508352789999989)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.073535866666674, longitude: -81.506221999999994)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.072601486018961, longitude: -81.508352789999989)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.073549352685632, longitude: -81.506221999999994)
> 
> 
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.07258800000001, longitude: -81.508352789999989)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.073535866666674, longitude: -81.506221999999994)
> 
> 
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.072614972037925, longitude: -81.508352789999989)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.073562838704596, longitude: -81.506221999999994)
> 
> 
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.072601486018961, longitude: -81.508352789999989)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.073549352685632, longitude: -81.506221999999994)
> 
> 
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.072628458056883, longitude: -81.508352789999989)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.073576324723554, longitude: -81.506221999999994)
> 
> 
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.072614972037925, longitude: -81.508352789999989)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.073562838704596, longitude: -81.506221999999994)
> 
> 
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.072641944075848, longitude: -81.508352789999989)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.073589810742519, longitude: -81.506221999999994)
> 
> 
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.072628458056883, longitude: -81.508352789999989)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.073576324723554, longitude: -81.506221999999994)
> 
> 
> After region change 
> 1) after adding all pins (cluster pins) on the map and scroll the map 
> UIView.animate
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.072655430094805, longitude: -81.508352789999989)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.073603296761476, longitude: -81.506221999999994)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.072641944075848, longitude: -81.508352789999989)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.073589810742519, longitude: -81.506221999999994)
> 
> 2)  after adding all pins (cluster pins) on the map and scroll the map 
> UIView.animate
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.072668916113777, longitude: -81.508352789999989)
> Location of toAdd Annotations  : CLLocationCoordinate2D(latitude: 41.073616782780441, longitude: -81.506221999999994)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.072655430094805, longitude: -81.508352789999989)
> Location of toRemove Annotations  : CLLocationCoordinate2D(latitude: 41.073603296761476, longitude: -81.506221999999994)

Kindly help me Please. 

Thank you. 

![pin changes](https://user-images.githubusercontent.com/13691970/31596641-66f6d17e-b261-11e7-922b-30e92b9404e2.gif)

**Comment by efremidze** [comment]
Will fix in next version

**Comment by efremidze** [comment]
try latest release [2.0.1](https://github.com/efremidze/Cluster/releases/tag/2.0.1)
