### ISSUE TITLE
Several exceptions

### ISSUE THREAD

**Issue by jose46moreno** [efremidze/Cluster#56]
I run the app, load the annotations in manager and the apps wrong.

This is a capture of this, with the line when is the error.

<img width="1440" alt="captura de pantalla 2017-10-20 a las 13 27 27" src="https://user-images.githubusercontent.com/8105593/31819019-f56c0ef6-b59a-11e7-9b72-04616ea2bf0e.png">

**Comment by efremidze** [comment]
Still?

**Comment by jose46moreno** [comment]
Same no. I am going to continue testing.
