### ISSUE TITLE
Cluster goes crazy

### ISSUE THREAD

**Issue by jose46moreno** [efremidze/Cluster#57]
I try latest release 2.0.1 and the cluster goes crazy. When I zoom on the map, it does not stop changing its position.

Help, please.

**Comment by efremidze** [comment]
Why did u make this ticket? U already mentioned the issue in https://github.com/efremidze/Cluster/issues/52.

**Comment by jose46moreno** [comment]
I am sorry. As the other ticket was closed, I did not know if you were still reading it.
