### ISSUE TITLE
When single annotation tapped, how do I get the index of the backing data

### ISSUE THREAD

**Issue by fraserscottmorrison** [efremidze/Cluster#59]
When single annotation tapped, how do I get the index of the backing array of data

### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description
I have an array of objects, e.g. `Shop` object, and for each I have created an Annotation object and added them to the ClusterManager
When user taps on a single annotationView and `mapView: didSelect:` is called, how do I get the correct index of the `Shop` array? This should be the Shop at the coordinates that the user has tapped on

### Environment

- **iOS Version**: Any
- **Device(s)**: Any

**Comment by efremidze** [comment]
`mapView.annotations` doesn't necessarily return an array in the same order as your `Shop` array. You could filter the `Shop` array to find the `Shop` associated with the Annotation. [Check this out](https://stackoverflow.com/questions/42068857/find-index-of-annotation-mapkit)

**Comment by fraserscottmorrison** [comment]
Thanks. I ended up subclassing Annotation to keep track of the array index

```swift
class SingleAnnotation : Annotation {
    let index: Int
}
```
