### ISSUE TITLE
Remove a single annotation

### ISSUE THREAD

**Issue by jVirus** [efremidze/Cluster#6]
It would be very useful to have an additional `API` method for removing a single `annotation`. Right now there is a single method called `removeAll()`, but I suggest to add a new method with the following signature: `remove(_ annotation: MKAnnotation)`.  

It would complement the existing `API` similar to the one used in `MKMapView` (`mapView.remove(annotation)`).

Thank you!

**Comment by efremidze** [comment]
Will be included in version 1.0.4
