### ISSUE TITLE
Will this work for google maps ?

### ISSUE THREAD

**Issue by Prudhvi1997** [efremidze/Cluster#74]
### New Issue Checklist

- [ ] I updated Cluster to the latest version.
- [ ] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [ ] I read the [documentation](https://github.com/efremidze/Cluster).
- [ ] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Environment

- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: [INSERT DEVICE(S) HERE]

**Comment by efremidze** [comment]
This won't work with Google Maps, however Google Maps released their own clustering library:
https://github.com/googlemaps/google-maps-ios-utils
