### ISSUE TITLE
I propose to make style property of ClusterAnnotationView - private

### ISSUE THREAD

**Issue by nikitabelosludtcev** [efremidze/Cluster#75]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description
Now the "style" variable is public with private(set) attribute.
The problem is when user call configure(with style: ClusterAnnotationStyle) with some style (.image or .color) he expects that style property will be updated too, but it's not happen.
@efremidze  What do you think?
I am writing Unit test for Cluster now and I find it confusing.

**Comment by efremidze** [comment]
Good point, ill fix that

**Comment by efremidze** [comment]
Fixed in latest commit
