### ISSUE TITLE
Exact Same Location problem

### ISSUE THREAD

**Issue by sandman4sure** [efremidze/Cluster#77]
regarding issue: #29

Can you add an option to disable this behavior?
When I have a cluster with around 50 points in the exact same location it forms a circle around this point. This is not always wanted. For an application which shows houses for sale, some will now be placed in water etc. (see images, first wanted behavior, second the circle)
When I zoom even further on the location the houses should be I won't even see any pins because they fall out of my visible rect.

I created a method which handles his own click on the cluster to it will show all houses on that location. 

I can bypass this behavior now by not using the Annotation class because of:
`(node as? Annotation)?.coordinate = node.coordinate.coordinate(onBearingInRadians: bearing, atDistanceInMeters: distanceFromContestedLocation)`
but am afraid that this may break in the future

![screen shot 2018-06-04 at 11 51 24](https://user-images.githubusercontent.com/223741/40910994-f133a438-67ed-11e8-8710-c4447ceeb024.png)
![screen shot 2018-06-04 at 11 52 59](https://user-images.githubusercontent.com/223741/40910993-f11c846a-67ed-11e8-91eb-492e425a9dab.png)

**Comment by efremidze** [comment]
New release 2.2.4 includes an option to disable it.
