### ISSUE TITLE
Swift compiler error

### ISSUE THREAD

**Issue by 0fcourse** [efremidze/Cluster#79]
After installing the library I got the below compiler errors, where my project targeting iOS 10 and use swift 3.3.
I have tried to update the pod repos after the installation but the issue still there.

**- Ambiguous use of 'addOperation'**
**- /mystorageplace/Pods/Cluster/Sources/Extensions.swift:125:10: Method 'addOperation' with Objective-C selector 'addOperation:' conflicts with previous declaration with the same Objective-C selector**

**Comment by efremidze** [comment]
Thanks, I'll take a look.

**Comment by efremidze** [comment]
Fixed in 2.2.6
