### ISSUE TITLE
Square annotations are overlapping each other but not clustering

### ISSUE THREAD

**Issue by matt-luo** [efremidze/Cluster#81]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description

I have made custom annotations that display a 50x50 image on the map but I was wondering if there was anyway I can override/set the collision radius so if the images overlap as shown in the picture below, they will cluster. As of now, they are overlapping but aren't clustering. Any tips/suggestions are greatly appreciated! 

<img width="280" alt="screen shot 2018-07-12 at 4 08 31 pm" src="https://user-images.githubusercontent.com/25110429/42664135-01afd8b8-85ee-11e8-832a-af545c3a2fa3.png">

### Environment

- **iOS Version**: [11.4]
- **Device(s)**: [iPhone 7]

**Comment by efremidze** [comment]
Did you try setting the cellSize property?
`manager.cellSize = CGSize(width: 50, height: 50)`

**Comment by matt-luo** [comment]
Hey thanks for the reply! It doesn't seem to work as cellSize is type Double? and assigning it CGSize does not work. Is there something else that I'm missing here?

**Comment by matt-luo** [comment]
I have a few follow up questions as well. It seems that even if cellSize were a CGSize, no where directly in the code does it try to access cellSize.width or cellSize.height so would it even be possible to create this collision radius? I'm also experimenting with dynamically changing the cellSize accordingly to the appropriate zoomLevel, does that sound like a feasible thing to do? Thanks again!
