### ISSUE TITLE
unclustering not working for some very close points

### ISSUE THREAD

**Issue by DavidTomic** [efremidze/Cluster#82]
unclustering not working for some very close points

e.g.
for `minCountForClustering = 3` this points won't uncluster:

```
CLLocationCoordinate2D(latitude: 43.893036806200001, longitude: 20.34926420108)
CLLocationCoordinate2D(latitude: 43.89306377823393, longitude: 20.349264201048999)
CLLocationCoordinate2D(latitude: 43.893009834158079, longitude: 20.349264201048999)
```

or e.g.

for `minCountForClustering = 2` this points won't uncluster:

```
CLLocationCoordinate2D(latitude: 45.804680699999999, longitude: 15.9769924)
CLLocationCoordinate2D(latitude: 45.804679899999996, longitude: 15.9769963)
```

### Environment

- **iOS Version**: [11.4.1]
- **Device(s)**: [iPhone 8]

**Comment by efremidze** [comment]
Released [2.3.0](https://github.com/efremidze/Cluster/releases/tag/2.3.0). Let me know if you still see the bug.
