### ISSUE TITLE
Documentation: Link to example is outdated

### ISSUE THREAD

**Issue by ernekjanR** [efremidze/Cluster#85]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description

Cluster Documentation includes a link to example. When clicked, it throws error 404 (link: https://efremidze.github.io/Cluster/Example/). Probably just outdated address. (new: https://github.com/efremidze/Cluster).

### Environment

Safari 11.1.1
- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: [INSERT DEVICE(S) HERE]

**Comment by efremidze** [comment]
Thanks I'll push a fix.
