### ISSUE TITLE
How to implement multiple pins in the same coordinates?

### ISSUE THREAD

**Issue by zhouhao27** [efremidze/Cluster#88]
I'd like to check if there is any implementation for multiple pins in the same coordinates? I think clustering is not enough.

**Comment by efremidze** [comment]
ClusterManager includes a property to distribute annotation on the same coordinate.
`clusterManager .shouldDistributeAnnotationsOnSameCoordinate = true`

**Comment by zhouhao27** [comment]
@efremidze Thanks. I'll have a try.

**Comment by zhouhao27** [comment]
@efremidze It works. But I'm wondering if there are any iOS implementation of Spiderfier?

**Comment by efremidze** [comment]
Hi, I can look into adding Spiderfy as an option. I haven't seen this on iOS though.

**Comment by zhouhao27** [comment]
@efremidze There is no Spiderfy solution in iOS yet. That's a great feature if any. Thanks.
