### ISSUE TITLE
Clusters/annotations not disappearing when they should

### ISSUE THREAD

**Issue by ivanmkc** [efremidze/Cluster#90]
Some clusters don't disappear (for example, when zoomed past the maximum zoom level for clustering). 

### Issue Description
I believe this is a symptom of annotations being added/removed while the mapview is being reloaded. The 'visibleAnnotations' array loses track of the added annotations\clusters and so they never disappear from then on.

### Environment

- **iOS Version**: iOS 11
- **Device(s)**: iPad Air

**Comment by efremidze** [comment]
Thanks I'll take a look.

**Comment by efremidze** [comment]
Released [2.3.0](https://github.com/efremidze/Cluster/releases/tag/2.3.0). Let me know if you still see the bug.

**Comment by kylemay-gridstone** [comment]
Experienced this in 2.3.0 😞
Had 6 items close to each other that were clustered when the map loaded up (due to zoom level being showing the whole country), and then it zoomed in, unclustered the items but still shows the cluster annotation.
