### ISSUE TITLE
Crash in QuadTreeNode annotations(in rect: MKMapRect)

### ISSUE THREAD

**Issue by kylemay-gridstone** [efremidze/Cluster#92]
### New Issue Checklist

- [x] I updated Cluster to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/Cluster/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/Cluster).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/Cluster/issues).

### Issue Description

I have noticed a few times that there has been a crash in `QuadTree.swift:132`
The line is 
`for annotation in annotations where rect.contains(annotation.coordinate)`
and the crash is due to index out of bounds. Presumably this is due to iterating the `annotations` array while it is being modified. Perhaps a copy of this array should be made inside the method to be used for the iteration. I'm not sure if this fixes it.

I cannot replicate this, however it has happened on multiple versions including the latest, 2.2.9. When this happened today the map was in memory but not visible on screen (page view controller sho8wing another page).

### Environment

- **iOS Version**: 12.0, have seen it on 11 also
- **Device(s)**: iPhone 8, iPad Mini 4

**Comment by efremidze** [comment]
Thanks for reporting. Currently fixing this issue. Related to https://github.com/efremidze/Cluster/pull/91.

**Comment by efremidze** [comment]
Released [2.3.0](https://github.com/efremidze/Cluster/releases/tag/2.3.0). Let me know if you still see the crash.

**Comment by petrovRV** [comment]
@efremidze I have the same problem, I updated Cluster to the latest version (Cluster (2.4.0)).
[https://drive.google.com/open?id=1JVSrB7vGc71UO7Jm93_5weLcaevItpnb](screen)

**Comment by efremidze** [comment]
I recently noticed it's still occurring. I'll fix it today.

**Comment by antoine20001** [comment]
Same issue on Cluster (2.4.0), iPhone XR iOS 12.1

**Comment by petrovRV** [comment]
Hello. @efremidze. Do you have some news about this problem?

**Comment by efremidze** [comment]
I've improved thread safety in [2.4.1](https://github.com/efremidze/Cluster/releases/tag/2.4.1). I believe it fixes any crashes.
